rawdata: "/Users/kimik/Library/CloudStorage/GoogleDrive-kimiaazargarzadeh@gmail.com/My Drive/retrep/rawdata"
intermediatedata: "/Users/kimik/Library/CloudStorage/GoogleDrive-kimiaazargarzadeh@gmail.com/My Drive/retrep/intermediatedata"
outputdata: "/Users/kimik/Library/CloudStorage/GoogleDrive-kimiaazargarzadeh@gmail.com/My Drive/retrep/outputdata"
