rawdata: G:\.shortcut-targets-by-id\1UGjf9COV14whS-Q0GMoVQ4jL8pAGnmbw\retrep\rawdata
intermediatedata: G:\.shortcut-targets-by-id\1UGjf9COV14whS-Q0GMoVQ4jL8pAGnmbw\retrep\intermediatedata
outputdata: G:\.shortcut-targets-by-id\1UGjf9COV14whS-Q0GMoVQ4jL8pAGnmbw\retrep\outputdata
